APPLICATION:
  HOST: localhost
  PORT: 8000

MYSQL:
  HOST: localhost
  PORT: 3306
  USERNAME: root
  PASSWORD: '123456'
  DATABASE: platform_algorithm
  LOGGING: true
  SYNCHRONIZE: false

REDIS:
  HOST: 127.0.0.1
  PORT: 6379
  DATABASE: 0
